# Generated by Django 3.0.8 on 2020-08-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Address',
        ),
    ]
